# Install Config
version: 5
name: Polaris
author: zloeber
# Configurtaion
config:
  # Enabled Tasks
  tasks:
    update: true
    upgrade: true
    # Add Repos
    # individual repos flags are mentioned under config.add_repo key
    repo: true
    # Add PPAs
    ppa: true
    # APT Packages
    apt: true
    # Whether to purge packages mentioned in config.purge key
    purge: true
    debs: true
    pip2: true
    pip3: true
    binaries: true
  # Repository Flags
  add_repo:
    winehq: false
    docker: true
    mendeley: false
    googlecloud: true
    spotify: false
    vscode: true
    skype: false
    signal: true
    insync: false
    google: true
    kubernetes: false
  # Flags
  flags:
  # Simulate flag will never be overridden by remote config.
    purge_enabled: true
    preserve_debs: true
    auto_yes: true

  # Packages to purge
  purge:
    - gnome-mines
    - gnome-sudoku
    - aisleriot
    - gnome-mahjongg
  # PPA List
  ppa:
    - ppa:dawidd0811/neofetch
    #- ppa:yubico/stable
    - ppa:teejee2008/ppa
  # Install components
  # APT Packages, Python Modules, Debian packages
  install:
    # Python 2 Modules
    python2:
      - docker-compose
      - awscli
    # Python 3 Modules
    # Debian packages:  .deb files
    # CSV format similar to lists
    #debian_packages:
    #  - https://atom-installer.github.com/v1.28.0/atom-amd64.deb,Atom-Editor.deb
    #  - https://download.teamviewer.com/download/teamviewer_i386.deb,Teamviewer.deb
    # Static Binaries which will be placed in /usr/local/bin
    # minikube, docker-compose, etc.
    # Follows same pattern as Debian packages
    # Name to be saved is second field
    apt:
      # Admin related Stuff
      administration:
        - dconf-editor
        - htop
        - apt-xapian-index
        - gdebi
        - gparted
        - synaptic
        - bleachbit
        - terminator
        - openssh-server
        - ubuntu-restricted-addons
        - ubuntu-restricted-extras
        - fdupes
        - libdvd-pkg
        - curl
        - jq
        - zsh
        - snapd
      # Security Related Stuff
      security:
        - nmap
        - zenmap
      # Productivity & Office Tools.
      productivity:
        - pandoc-data
        - pandoc
        #- texstudio
        #- texlive-fonts-extra
        #- texlive-formats-extra
        #- texlive-fonts-recommended
        #- texlive-science
        #- texlive-generic-extra
        #- texlive-xetex
        #- texlive-luatex
        #- texlive-pstricks
        #- texlive-science
        #- texlive-extra-utils
        #- texlive-lang-english
        #- texlive-lang-other
        #- texlive-font-utils
        #- texlive-publishers
        #- gummi
      # Multimedia Tools. Photo Editors Converting tools, plex etc.
      multimedia:
        - audacity
        - vlc
        - vlc-plugin*
        - devede
        - soundconverter
        - ffmpegthumbnailer
        - gimp
        - handbrake
        - handbrake-cli
        #- rawtherapee
        #- darktable
        #- mpv
      # Tools related to development.
      development:
        - curl
        - spyder
        - spyder3
        - git
        - shellcheck
        - clinfo
        - vainfo
        - vdpauinfo
        - python-magic
        - s3cmd
        - python3-pip
        - python-dateutil
        - python-pip-whl
        - python-pip
      # Everything Else
      # Which is conditional
      other:
      #  - gnome-online-miners
      # Packages supplied by external repositories & PPAs
      # Dont Mix packages provided by distribution and PPAs
      # Sometimes external repos and ppas fail, so better isolate it.
      external:
        - google-chrome-stable
        - code
        - google-cloud-sdk
        - gcsfuse
        - docker-ce
