apiVersion: v1
kind: Service
metadata:  
  name: dashboard-443to4443
spec:
  selector:    
    app: k8s-dashboard
  type: NodePort
  ports:  
  - name: https
    port: 4443
    targetPort: 443
    nodePort: 30036
    protocol: TCP