apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-zacharyloeber-com
spec:
  secretName: k8s-zachary-loeber-crt
  dnsNames:
  - k8s.zacharyloeber.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - k8s.zacharyloeber.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
